---
title: "SPiCT_hake"
author: "Mitsuyo Miyagawa"
date: "`r Sys.Date()`"
output: 
  md_document:
    toc: true
    variant: markdown_github
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
                     cache=TRUE,
               cache.lazy=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.width=10,
               fig.height = 7.5, 
               out.width='80%')
```

## 1．準備

```{r read data}

devtools::install_github("DTUAqua/spict/spict") #パッケージのインストール

library(spict)#ライブラリーの読み込み  

#1-1　例データの読み込み  

data(pol)
#pol$albacore #data of south atlantic albacore　データの単位はCが1000t, CPUEはkg/100hooks  
#$lobster #data on new zealand rock lobster データの単位はCがt  
pol$hake #data on nothern namibian hake　データの単位はCが1000t  

```
## 2. Hakeの解析

```{r plot_C_I}
#2-1.　例データのプロット  
plotspict.data(pol$hake)

```

```{r setting}
# 2-2.　time intervalの指定/確認  
inp<-check.inp(pol$hake)
inp$dtc

```
  

## 番外編. 濱邉さん推定K,qにfix,Schaefer型(n=2),Biomassの過程誤差とIndexの観測誤差あり,Fの過程誤差ありとCの観測誤差なし
```{r fit1}
# 2-3.　model fit  
# Base Case 
 inp <- pol$hake
 inp$priors$logn<-c(log(2),1e-3) #shape parameter=2 Schaefer型にshape parameterを固定
 
 inp$phases$logq<- -1 #logqを固定するフェーズの指定
 inp$phases$logK<- -1
 #inp$phases$logr<- -1

 inp$priors$logsdc<-c(log(0.001),1e-3)#logsdcをほぼ0にする
 inp$ini$logq <- log(0.0004248)
 #inp$ini$logr <- log(0.3335362)
 inp$ini$logK <- log(3562.6967130)
 inp$priors$logbeta<-c(1,1,0)
 res_hake<-fit.spict(inp)

# summary of result
summary(res_hake)

```

```{r hake_fit1}
# 2-4.　plot results
plot(res_hake) #全体的な結果のプロット
plotspict.priors(res_hake)#shape parameter(n)とalpha,betaの事前分布と事後分布
```

```{r hake_residual}
# 2-5.　Residuals and diagnostics 残差診断
res<-calc.osa.resid(res_hake)
plotspict.diagnostic(res)
```

```{r hake_retro}
# 2-6.　Retrospective plots レトロ解析
res<-retro(res_hake,nretroyear=5)
plotspict.retro(res)
plotspict.retro.fixed(res)

mohns_rho(res,what=c("FFmsy","BBmsy")) #モーンズローの値
```